version: '3.9'

services:
  uno_app:
    container_name: uno_app
    image: uno-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://uno_db:5432/uno_db
      - DATABASE_USERNAME=sebastian
      - DATABASE_PASSWORD=password
    depends_on:
      - uno_db
  uno_db:
    container_name: uno_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uno_db