spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uno_db
    username: sebastian
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always






#spring:
#  datasource:
#    url: jdbc:h2:file:~/Documents/H2_Databases/uno_app/uno_db
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#  output:
#    ansi:
#      enabled: always

#logging:
#  pattern:

#    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){cyan} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){magenta}%n"
